### ISSUE TITLE
Update settings from config file

### ISSUE THREAD

**Issue by drewejohnson** [CORE-GATECH-GROUP/serpent-tools#57]
Currently, the settings loader has to take settings one at a time. For the sake of consistency and ease, it would be nice to have the `rc` settings loader take a file path argument and load all settings from there.

I think a `yaml` file would be pretty straight forward, since we already use the `pyyaml` module. The loader could be setup to read in a strict, full name manner,
```
depletion.metadataKeys: ['ZAI', 'NAMES']
depletion.materials: ['fuel*', 'bp1']
verbosity: 'error'
...
```
or with nested levels
```
depletion:
    metadataKeys: ['ZAI', 'NAMES']
    materials: ['fuel*', 'bp1']
verbosity: 'error'
...
```
The two implementations should have the same result, just that in the second case there is some reconstructing that has to be done behind the scenes.
